#ifndef MDPLIB_RAWFILEMOPROBLEM_H
#define MDPLIB_RAWFILEMOPROBLEM_H

#include <vector>

#include "../../State.h"
#include "../../Problem.h"

#include "../MObjProblem.h"
#include "../MObjState.h"

namespace mlmobj
{

/**
 * Class that implements MDP problems described using the format generated by:
 * https://github.com/kylewray/librbr/blob/master/librbr/src/management/raw_file.cpp
 */
class RawFileMOProblem : public MOProblem
{
private:

    int indexS0_;

    int nActions_;

public:

    using MOProblem::goal;

    RawFileMOProblem(char* filename);

    virtual ~RawFileMOProblem() { }

    /**
     * Overrides method from MOProblem.
     */
    virtual double cost(mlcore::State* s, mlcore::Action* a, int i) const;

    /**
     * Overrides method from MOProblem.
     */
    virtual mlcore::SuccessorsList transition(mlcore::State* s, mlcore::Action* a, int index);

    /**
     * Overrides method from MOProblem.
     */
    virtual bool goal(mlcore::State* s, int index) const;

    /**
     * Overrides method from MOProblem.
     */
    virtual bool applicable(mlcore::State* s, mlcore::Action* a) const;
};

}

#endif // MDPLIB_RAWFILEMOPROBLEM_H
