#ifndef MDPLIB_RAWFILELEXIPROBLEM_H
#define MDPLIB_RAWFILELEXIPROBLEM_H

#include <vector>

#include "../../state.h"
#include "../../problem.h"

#include "../lexi_state.h"
#include "../lexi_problem.h"

namespace mllexi
{

/**
 * Class that implements MDP problems described using the format generated by:
 * https://github.com/kylewray/librbr/blob/master/librbr/src/management/raw_file.cpp
 */
class RawFileLexiProblem : public LexiProblem
{
private:

    int indexS0_;

    int nActions_;

public:

    using LexiProblem::goal;

    RawFileLexiProblem(char* filename);

    virtual ~RawFileLexiProblem() { }

    /**
     * Overrides method from LexiProblem.
     */
    virtual double cost(mlcore::State* s, mlcore::Action* a, int i) const;

    /**
     * Overrides method from LexiProblem.
     */
    virtual mlcore::SuccessorsList transition(mlcore::State* s, mlcore::Action* a, int index);

    /**
     * Overrides method from LexiProblem.
     */
    virtual bool goal(mlcore::State* s, int index) const;

    /**
     * Overrides method from LexiProblem.
     */
    virtual bool applicable(mlcore::State* s, mlcore::Action* a) const;
};

}

#endif // MDPLIB_RAWFILELEXIPROBLEM_H
