#ifndef MDPLIB_PROBLEM_H
#define MDPLIB_PROBLEM_H

#include <list>
#include "../include/state.h"
#include "../include/action.h"
#include "../include/util/rational.h"

/**
 * An abstract class for Stochastic Shortest Path Problem objects.
 */
class Problem
{
public:
    Problem();
    virtual ~Problem();
    Problem(const Problem& other);
    Problem& operator=(const Problem& other);

    /**
     * Returns true if state s is a goal.
     */
    virtual bool goal(const State *s) const =0;

    /**
     * Returns a list of all succcessors when action a is applied in state s.
     */
    virtual std::list<Successor> transition(State *s, Action *a) const =0;

    /**
     * Returns the cost of applying action a in state s.
     */
    virtual Rational cost(State *s, Action *a) const =0;

    /**
     * Returns true if action a can be applied in state s.
     */
    virtual bool applicable(State *s, Action *a) const =0;

protected:
    /**
     * The initial state for the problem.
     */
    State *s0;

    /**
     * A list of all the possible actions in this problem.
     */
    std::list<Action *> actions;

    /**
     * An internal structure to store any states that are generated by the
     * transition function.
     */
    StateSet states;

    /**
     * Returns the copy of the given state if it exists, or adds it to the state set
     * and returns it if it doesn't;
     */
     const State * getState(const State *s)
     {
        states.insert(s);
        return *states.find(s);
     }

};

#endif // MDPLIB_PROBLEM_H
